Pypi scraper
openteamsinc/opensourcescore.dev pull request #17
Opened 2024-07-18 17:25 UTC by karamba228

This is the PyPi CLI scraper tool, I recommend using the web scraper as it yields more useful information. There are some fields like list of dependencies that can only be received from the json scrape. At the moment the output files are sorted into 2 separate folders depending on the source, I am planning to combine that functionality

To run the scraper install the conda environment and run the `cli.py`

2024-07-18 19:33 UTC, srossross commented on environment.yml
> +dependencies:
Can we just use pip requirements.txt for this? and specify the top level requirements.


however I'm not familiar with conda as much any more, can you describe how this file is generated?

2024-07-18 19:44 UTC, srossross requested changes
Hey @karamba228 thanks for the PR. 

It looks like a great start. 

I've left a lot of comments as I will be leaving tomorrow, in general, lets remove a lot of the complexity  

for example lets try not to guess that we will need csv and just adress that when it comes.

also for pandas please use `partition_cols=` instead of writing your own partitioner

2024-07-18 19:44 UTC, srossross commented on score/cli.py
> +def parse_letters(letters_str):
what is this function doing, can you give it a better name?

2024-07-18 19:44 UTC, srossross commented on score/cli.py
> +def run_cli():
please revert this and use the click group

the command will be `python -m score.cli scrape_pypi` or `python -m score.cli scrape_pypi_web`

2024-07-18 19:44 UTC, srossross commented on score/cli.py
> +    )
just use parquet

2024-07-18 19:44 UTC, srossross commented on score/cli.py
> +    method = click.prompt(
please dont use prompts this should be runnable from the a remote worker

2024-07-18 19:44 UTC, srossross commented on score/cli.py
> +    save_config(config)
what is the purpose of this block? lets remove for now if possible

2024-07-18 19:44 UTC, srossross commented on score/cli.py
> +        web_thread.join()
this is OK for now, but we will use `google cloud run` to do multi process

2024-07-18 19:44 UTC, srossross commented on score/data_storage/parquet_storage.py
> +def save_to_parquet(df, letter, max_records_per_parquet, output_dir):
This is OK for now, please look into duckdb hive partitioning

2024-07-18 19:44 UTC, srossross commented on score/mian.py
> +    run_cli(args.config)
this is handled by click. please remove this file

2024-07-23 16:48 UTC, srossross requested changes
Thanks for the previous fixes. Please let me know if you have any blockers for the partioning, this can be done with pandas `to_parquet` or duckdb

2024-07-23 16:48 UTC, srossross commented on score/cli.py
> +def input_formatter(letters_str):
```suggestion
def expand_and_sort_character_set(letters_str):
```

2024-07-23 16:48 UTC, srossross commented on score/data_storage/parquet_storage.py
> +def save_to_parquet(df, letter, output_dir):
why is letter an argument here? shouldn;t this be gotten from the package name?

2024-07-23 16:48 UTC, srossross commented on score/data_storage/parquet_storage.py
> +                    df[column] = df[column].astype(str).fillna("")
This should not be required, what issues are you getting?

2024-07-23 16:48 UTC, srossross commented on score/data_storage/parquet_storage.py
> +        con.execute(f"CREATE TABLE existing_data AS SELECT * FROM '{parquet_file}'")
please use hive partitioning, or please let me know what the issue is with writing partiions

2024-07-23 16:48 UTC, srossross commented on score/cli.py
> +def input_formatter(letters_str):
this function is also defined in `utils.common`

2024-07-23 16:48 UTC, srossross commented on score/utils/common.py
> +def get_next_parquet_filename(base_name, extension=".parquet"):
this does not look used

2024-07-23 16:48 UTC, srossross commented on score/data_storage/parquet_storage.py
> +    parquet_file = os.path.join(output_dir, f"pypi_packages_{letter}.parquet")
this is not needed if you use partitioning

2024-07-24 17:47 UTC, karamba228 commented on score/cli.py
> +def input_formatter(letters_str):
This function has been removed from cli.py and kept in `utils.common`

### Reasoning for this function and function name:
* It formats user input to get the range of letters to scrape (Ex. "a,x-z" input should allow the scraper to get data for letters a, x, y, and z ).

2024-07-24 17:55 UTC, karamba228 commented on score/data_storage/parquet_storage.py
> +def save_to_parquet(df, letter, output_dir):
The scraper gets a list of all the packages and runs threads for each letter. Since the letter is already stored as a variable in the scraper, we can pass it to `save_to_parquet` for hive partitioning instead of having it scan the data again for the first letter.

2024-07-24 18:07 UTC, karamba228 commented on score/data_storage/parquet_storage.py
> +    parquet_file = os.path.join(output_dir, f"pypi_packages_{letter}.parquet")
I will still need to use line 24:
```
parquet_file = os.path.join(partitioned_dir, "pypi_packages.parquet")
```

It is used for appending data into the Parquet file. The scraper does not accumulate the data; it just processes it. Because with a large amount of data, if something goes wrong, not all data is lost and we can resume the process. DuckDB does not allow for appending to the Parquet file. It can write into it as a lump of data. So the workaround is, while using Hive partitioning for the file structure, we can use pandas for reading the Parquet data, appending the currently processed package, and writing the new combined data by overwriting the file.

2024-07-25 13:18 UTC, srossross commented on score/data_storage/parquet_storage.py
> +    parquet_file = os.path.join(output_dir, f"pypi_packages_{letter}.parquet")
That is the point of the partition, we won't need to append to the parquet file. if we partition on the first letter of the package name, we can just overwrite for that letter.

please don't worry about resuming the process, or multi threading at this point

2024-07-25 13:20 UTC, srossross commented on score/data_storage/parquet_storage.py
> +def save_to_parquet(df, letter, output_dir):
But won't this just be the same as `df['name'].str[0]` why pass it in? or for the hive partition, this should be stored in the partition column `df['first_letter']`

2024-07-26 00:22 UTC, srossross requested changes
let's simplify

2024-07-26 00:22 UTC, srossross commented on score/data_storage/parquet_storage.py
> +def save_to_parquet(df, letter, output_dir):
Please remove this logic/function and just use df.to_parquet(output_dir, partition_cols=['first_letter'])

2024-07-26 00:22 UTC, srossross commented on score/utils/config_utils.py
> +import yaml
this file is unused

2024-07-26 00:22 UTC, srossross commented on score/utils/common.py
> +    """
OK, I see what this is doing, but I am worried about the complexity 

for example it looks like there will be unhanded bugs 

* `input_formatter("a-0") -> ''`
* `input_formatter("Z-a") -> 'Z[\\]^_`a'`
* 

can we remove this function and just allow a single letter input eg  instead of 

```
cli ... --letters a-c
```

Just use `--start 0 --end 3`

```
partitions = string.ascii_lowercase + string.digits

partitions[args.start: args.end]
string. string.digits
```

this will also work better with job parallelization with Apache airflow or gcp jobs

2024-07-26 00:39 UTC, srossross commented on score/data_retrieval/web_scraper.py
> +def process_packages_by_letter(letter, package_names, config, output_dir):
sorry a few more - please remove the `ThreadPoolExecutor` in `scrape_web(` above and just call this directly

2024-07-26 00:41 UTC, srossross commented on score/data_retrieval/web_scraper.py
> +            save_to_parquet(df, letter, output_dir)
```suggestion
    all_package_data = []
    for package_name in tqdm(letter_package_names, desc=f"Processing letter {letter}"):
        package_data = get_package_data(package_name)
        if package_data:
           all_package_data.append(package_data)
        
    df = pd.DataFrame(all_package_data)
    df.to_parquet(output_dir, partition_cols=['first_letter'])
```

2024-07-31 12:13 UTC, srossross approved these changes

2024-08-02 13:35 UTC, merged