created conda scrapper
openteamsinc/opensourcescore.dev pull request #37
Opened 2024-07-30 13:28 UTC by siddheshghadi751

2024-08-06 14:57 UTC, srossross requested changes

2024-08-06 14:57 UTC, srossross commented on score/conda.py
> +        logger.error("Error fetching package names: %s", e)
Why catch this exception? this will continue the process with no packages to build

2024-08-06 14:57 UTC, srossross commented on score/conda.py
> +            packages_name_list = []
see #17 use `response.raise_for_status()`

2024-08-06 14:57 UTC, srossross commented on score/cli.py
>  OUTPUT_ROOT = Path(os.environ.get("OUTPUT_ROOT", "."))
see #4 please move this to `cli.py` and pass it in as an argument

2024-08-06 14:57 UTC, srossross commented on score/common.py
> +import pandas as pd
This function looks like it is just obfuscating the code and is unnecessary, lets just add the two lines inline

2024-08-06 14:57 UTC, srossross commented on score/cli.py
> +        click.echo(f"Error: {e}")
please don't catch and ignore exceptions

2024-08-06 15:53 UTC, siddheshghadi751 commented on score/conda.py
> +        logger.error("Error fetching package names: %s", e)
removed this now. Its not needed.

2024-08-06 16:18 UTC, srossross commented on requirements.txt
> +websocket-client==1.8.0
most of these packages look unused

2024-08-06 16:19 UTC, siddheshghadi751 commented on requirements.txt
> +websocket-client==1.8.0
I will remove them. Most packages got added due to installation of some used packages and their dependencies and when we do `pip freeze > requirements.txt` these extra packages got added

2024-08-06 16:53 UTC, siddheshghadi751 commented on score/cli.py
>  OUTPUT_ROOT = Path(os.environ.get("OUTPUT_ROOT", "."))
Its already in `cli.py`

2024-08-06 17:25 UTC, srossross commented on requirements.txt
> +bs4~=0.0.2
what is this?

2024-08-06 17:29 UTC, srossross requested changes
looks good. I've requested a few minor changes

2024-08-06 17:29 UTC, srossross commented on score/conda.py
> +logger.addHandler(logging.FileHandler("conda.log"))
Please remove this, it should be handled already by setup_logging in the cli.py

2024-08-06 17:29 UTC, srossross commented on score/conda.py
> +        logger.error("Failed to save data for package letter : %s", letter_to_scrape)
this should no longer be required
```suggestion

    df = pd.DataFrame(package_data_list)
    df.to_parquet(output_dir, partition_cols=["initial_letter"])
    logger.info("Data saved for package : %s", len(package_data_list))
```

2024-08-06 17:29 UTC, srossross commented on requirements.txt
> +numpy~=2.0.1
there are no numpy imports

2024-08-07 05:16 UTC, siddheshghadi751 commented on score/conda.py
> +        logger.error("Failed to save data for package letter : %s", letter_to_scrape)
This is updated now

2024-08-07 06:03 UTC, siddheshghadi751 commented on requirements.txt
> +bs4~=0.0.2
beautifulsoup

2024-08-07 06:06 UTC, siddheshghadi751 commented on requirements.txt
> +numpy~=2.0.1
removed them

2024-08-07 06:09 UTC, siddheshghadi751 commented
> looks good. I've requested a few minor changes

Done

2024-08-07 13:27 UTC, srossross commented on score/conda.py
> +    packages_url = "https://raw.githubusercontent.com/conda-forge/feedstock-outputs/single-file/feedstock-outputs.json"
is this the correct conda url?

2024-08-07 14:14 UTC, siddheshghadi751 commented on score/conda.py
> +    packages_url = "https://raw.githubusercontent.com/conda-forge/feedstock-outputs/single-file/feedstock-outputs.json"
Yes, It is used in backend of conda-forge website.

2024-08-08 05:07 UTC, closed without merging