Created Vulnerabilities Scraper
openteamsinc/opensourcescore.dev pull request #53
Opened 2024-08-08 06:05 UTC by siddheshghadi751

* added conda scraper (#49)

* initial deploy (#51)

* initial deploy

* update run

* typo

* execute

* fix

* cloud build

---------

---------

2024-08-08 17:29 UTC, srossross requested changes
looks good. 💯  One minor request. 

I think that we might want to explore unpacking more data in the future, but the count_high, count_moderate, count_low works for now

2024-08-08 17:29 UTC, srossross commented on score/vulnerabilities/scrape_vulnerabilities.py
> +                "low": len([v for v in required_vuln if v == "LOW"]),
```suggestion
                "count_high": len([v for v in required_vuln if v == "HIGH"]),
                "count_moderate": len([v for v in required_vuln if v == "MODERATE"]),
                "count_low": len([v for v in required_vuln if v == "LOW"]),
```

2024-08-09 02:41 UTC, siddheshghadi751 commented on score/vulnerabilities/scrape_vulnerabilities.py
> +                "low": len([v for v in required_vuln if v == "LOW"]),
Its done now.

2024-08-09 12:34 UTC, srossross approved these changes

2024-08-09 12:44 UTC, merged