Feat/git update
openteamsinc/opensourcescore.dev pull request #71
Opened 2024-08-14 18:36 UTC by karamba228

2024-08-14 23:59 UTC, srossross requested changes

2024-08-14 23:59 UTC, srossross commented on score/git_vcs/scrape.py
> +            log.error(f"{url}: {err}")
why did you remove the 'Repo not found' error?

2024-08-14 23:59 UTC, srossross commented on score/git_vcs/scrape.py
> +            repo = Repo.clone_from(url, tmpdir, depth=1)
this is cloning the repo again right? can you move this so we don't clone the repo twice?

2024-08-15 02:47 UTC, karamba228 commented on score/git_vcs/scrape.py
> +            repo = Repo.clone_from(url, tmpdir, depth=1)
This is the fastest way to do this task. For the commit data we need to go full depth of the repository, so we do `no_checkout` for the fastest result. On the other hand to get the `License ` we need to check out the repo so we can read the file, but we can do `depth=1`  to speed it up. Doing 2 requests separately ends up being faster than doing a full depth checkout of some repositories.

I tested it with 13 different projects that had different types of licenses to make sure the detection is accurate.
#### Here are some time results I got:
* Without license detection (just retrieving the commit history): `3min 10s`
* With license detection but request separate: `7min 15s`
* With one request but full depth checkout: It had 6 projects processed at `7min 40s`

2024-08-15 13:33 UTC, srossross commented on score/git_vcs/scrape.py
> +            repo = Repo.clone_from(url, tmpdir, depth=1)
Thanks for the explanation:

On the bare repo can you just run:

```py
repo.git.checkout(repo.active_branch, "--", "LICENSE*")
```

this should get the licence and only check out `LICENSE.txt` or `LICENSE`

2024-08-15 13:34 UTC, srossross commented on score/git_vcs/scrape.py
> +            for blob in root_files:
Please do no not iterate over all blobs, just check for the existance of `LICENSE` or `LICENSE.txt` in the root directory with `os.path.exists`

2024-08-15 18:20 UTC, srossross commented on score/git_vcs/license_detection.py
> +def identify_license(license_content: str) -> str:
This https://github.com/licensee/licensee seems like a good ruby implementation of a licence checker, can you look into how to implement this in python?

2024-08-16 18:17 UTC, srossross approved these changes

2024-08-16 18:17 UTC, merged