Util/actions
openteamsinc/opensourcescore.dev pull request #96
Opened 2024-09-13 15:39 UTC by karamba228

2024-09-13 17:48 UTC, srossross commented on .github/actions/annotate/index.js
> +    });
can you replace this with the fetch builtin?
```suggestion
   const res = await fetch(url);
   return res.json()
```

2024-09-13 17:57 UTC, srossross requested changes
A few issues raised

Can you also please use the `package-ecosystem: pip` this should be configurable and raise an error if it is not supported

Also the requirements.txt does not check that the package names are valid eg

* `# This is a comment`
* `package# This is a comment after a package`
* `-i foo.com package`

please see https://pip.pypa.io/en/stable/reference/requirements-file-format/

2024-09-13 17:57 UTC, srossross commented on .github/actions/annotate/index.js
> +function makeApiRequest(packageName) {
Can you name this to reflect what it is doing `fetchPackageScore`

2024-09-13 17:57 UTC, srossross commented on .github/actions/annotate/index.js
> +    const packages = fs.readFileSync(filePath, 'utf-8').split('\n').filter(pkg => pkg);
Please use the async fs in an async function `const fs = require('fs/promises');`

then 

```suggestion
    const packages = (await fs.readFile(filePath, 'utf-8')).split('\n').filter(pkg => pkg);
```

2024-09-13 20:36 UTC, srossross requested changes

2024-09-13 20:36 UTC, srossross commented on .github/actions/annotate/action.yml
> +  using: "node12"
why 12? isn't 20 the current LTS version?

2024-09-13 20:36 UTC, srossross commented on .github/actions/annotate/index.js
> +    const ecosystem = process.env.PACKAGE_ECOSYSTEM || 'pip';
the example docs I sent say to use 

```ts
const core = require('@actions/core');
core.getInput('package-ecosystem', { required: true });
```

is there a reason you choose not to use that package?

2024-09-13 20:36 UTC, srossross commented on .github/actions/annotate/index.js
> +        console.log(`::error file=requirements.txt::Error looking up package ${packageName}: ${error.message}`);
we are trying to answer the question

> Will integrating project X as a dependency enhance the stability and maintainability of our applications while minimizing potential risks and challenges?

in the next PR lets adjust the errors to match the answer to this question better

2024-09-13 20:38 UTC, srossross commented on .github/actions/annotate/index.js
> +    }
Please do not hide errors behind log statements: https://en.wikipedia.org/wiki/Error_hiding

it looks like this is the appropriate call:

```
core.setFailed(`Action failed with error ${err}`);
```

2024-09-16 13:52 UTC, srossross commented on .github/actions/annotate/index.js
> +        console.log(`::error file=requirements.txt::Error looking up package ${packageName}: ${error.message}`);
opened #97

2024-09-16 17:57 UTC, srossross commented on .github/actions/annotate/dist/index.js.LICENSE.txt
> +/*! ws. MIT License. Einar Otto Stangvik <einaros@gmail.com> */
what is this?

2024-09-16 17:59 UTC, srossross commented on .github/actions/annotate/index.js
> +            core.notice(`Package ${packageName}: (Maturity: ${maturityValue}, Health: ${healthRiskValue}). ${recommendation}`);
There is no output. You need to include the file name and line number

see AnnotationProperties in https://www.npmjs.com/package/@actions/core

2024-09-16 18:00 UTC, karamba228 commented on .github/actions/annotate/dist/index.js.LICENSE.txt
> +/*! ws. MIT License. Einar Otto Stangvik <einaros@gmail.com> */
That got auto-filled with running the webpack command. do we have a specific license that we are using? Or should this just be removed completely?

2024-09-16 18:02 UTC, srossross commented on .github/actions/annotate/dist/index.js.LICENSE.txt
> +/*! ws. MIT License. Einar Otto Stangvik <einaros@gmail.com> */
this should be removed, but I will add a MIT license in the main dir

2024-09-16 18:03 UTC, srossross commented on .github/actions/annotate/dist/index.js.LICENSE.txt
> +/*! ws. MIT License. Einar Otto Stangvik <einaros@gmail.com> */
actually I already set up a BSD 2-clause 

https://github.com/openteamsinc/Score/blob/main/LICENSE

2024-09-16 18:53 UTC, srossross commented on .github/actions/annotate/action.yml
> +  main: "dist/index.js"
it looks like you are missing the intputs here

```suggestion
name: "Annotate Requirements"
description: "Annotates the requirements.txt file using the Score API"
runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  package-ecosystem:
    description: ....
    required: true
```

2024-09-17 00:51 UTC, srossross approved these changes
This looks good, lets move it to https://github.com/openteamsinc/actions/

2024-09-17 17:54 UTC, srossross commented
moved to openteamsinc/actions#1

2024-09-17 17:54 UTC, closed without merging